quests = {
    [1] = {
        [1] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Razor Boar", ["Level"] = 1, ["Repeatable"] = true},
        [2] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Wolf", ["Level"] = 4, ["Repeatable"] = true},
        [3] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Tortoise", ["Level"] = 2, ["Repeatable"] = true},
        [4] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Brown Bear", ["Level"] = 7, ["Repeatable"] = true},
        [5] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Tortoise", ["Level"] = 3, ["Repeatable"] = false},
        [6] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Jackalope", ["Level"] = 20, ["Repeatable"] = false},
        [7] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Rock Golem", ["Level"] = 10, ["Repeatable"] = true},
        [8] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Wolf", ["Level"] = 6, ["Repeatable"] = false},
        [9] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Rock Golem", ["Level"] = 11, ["Repeatable"] = false},
        [10] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Crystal Boar", ["Level"] = 12, ["Repeatable"] = true},
        [11] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Thunder Sakura Moose", ["Level"] = 15, ["Repeatable"] = true},
        [12] = {["Type"] = "Kill", ["Amount"] = 20, ["Target"] = "Basilisk", ["Level"] = 23, ["Repeatable"] = false},
        [13] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Soldier Boar", ["Level"] = 21, ["Repeatable"] = true},
        [14] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Basilisk", ["Level"] = 22, ["Repeatable"] = true},
        [49] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Hagan", ["Level"] = 9, ["Repeatable"] = false},
        [50] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Galiard", ["Level"] = 14, ["Repeatable"] = false},
        [51] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Thunder Sakura Moose", ["Level"] = 17, ["Repeatable"] = false},
        [52] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Jackalope", ["Level"] = 18, ["Repeatable"] = true},
    },
    [2] = {
        [15] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Fire Wasp", ["Level"] = 23, ["Repeatable"] = true},
        [16] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Ember Jaguar", ["Level"] = 25, ["Repeatable"] = true},
        [17] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Lava Basilisk", ["Level"] = 28, ["Repeatable"] = true},
        [18] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Skeleton Bear", ["Level"] = 30, ["Repeatable"] = true},
        [19] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Fiery Moose", ["Level"] = 33, ["Repeatable"] = true},
        [20] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Magma Golem", ["Level"] = 36, ["Repeatable"] = true},
        [21] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Phoenix", ["Level"] = 38, ["Repeatable"] = true},
        [22] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Phoenix", ["Level"] = 40, ["Repeatable"] = false},
        [23] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Fire Imp", ["Level"] = 41, ["Repeatable"] = true},
        [24] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Hell Hound", ["Level"] = 42, ["Repeatable"] = true},
        [25] = {["Type"] = "Kill", ["Amount"] = 20, ["Target"] = "Hell Hound", ["Level"] = 43, ["Repeatable"] = false},
        [53] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Lava Basilisk", ["Level"] = 29, ["Repeatable"] = false},
        [54] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Fiery Moose", ["Level"] = 35, ["Repeatable"] = false},
        [55] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Roaring Ogre", ["Level"] = 27, ["Repeatable"] = false},
        [56] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Erebus", ["Level"] = 32, ["Repeatable"] = false},
    },
    [3] = {
        [26] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Mist Bunny", ["Level"] = 43, ["Repeatable"] = true},
        [27] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Penguin", ["Level"] = 45, ["Repeatable"] = true},
        [28] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Frost Scorpion", ["Level"] = 48, ["Repeatable"] = true},
        [29] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Snow Kitsune", ["Level"] = 50, ["Repeatable"] = true},
        [30] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Snow Kitsune", ["Level"] = 52, ["Repeatable"] = false},
        [31] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Chill Bat", ["Level"] = 53, ["Repeatable"] = true},
        [32] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Polar Bear", ["Level"] = 56, ["Repeatable"] = true},
        [33] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Cold Mammoth", ["Level"] = 58, ["Repeatable"] = true},
        [34] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Cold Mammoth", ["Level"] = 60, ["Repeatable"] = false},
        [35] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Ice Wraith", ["Level"] = 61, ["Repeatable"] = true},
        [36] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Icewhal", ["Level"] = 62, ["Repeatable"] = true},
        [37] = {["Type"] = "Kill", ["Amount"] = 20, ["Target"] = "Icewhal", ["Level"] = 63, ["Repeatable"] = false},
        [57] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Alpha Icewhal", ["Level"] = 47, ["Repeatable"] = false},
        [58] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Yeti", ["Level"] = 51, ["Repeatable"] = false},
        [59] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Penguin", ["Level"] = 47, ["Repeatable"] = false},
    },
    [4] = {
        [38] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Crocodile", ["Level"] = 63, ["Repeatable"] = true},
        [39] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Raptor", ["Level"] = 66, ["Repeatable"] = true},
        [40] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Desert Phoenix", ["Level"] = 69, ["Repeatable"] = true},
        [41] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Spirit Lion", ["Level"] = 71, ["Repeatable"] = true},
        [42] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Oasis Tortoise", ["Level"] = 74, ["Repeatable"] = true},
        [43] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Dragonfly", ["Level"] = 77, ["Repeatable"] = true},
        [44] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Camel", ["Level"] = 79, ["Repeatable"] = true},
        [45] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Camel", ["Level"] = 80, ["Repeatable"] = false},
        [46] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Tomb Scorpion", ["Level"] = 81, ["Repeatable"] = true},
        [47] = {["Type"] = "Kill", ["Amount"] = 5, ["Target"] = "Jeweled Scarab", ["Level"] = 82, ["Repeatable"] = true},
        [48] = {["Type"] = "Kill", ["Amount"] = 20, ["Target"] = "Jeweled Scarab", ["Level"] = 83, ["Repeatable"] = false},
        [60] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Desert Phoenix", ["Level"] = 70, ["Repeatable"] = false},
        [61] = {["Type"] = "Kill", ["Amount"] = 10, ["Target"] = "Oasis Tortoise", ["Level"] = 76, ["Repeatable"] = false},
        [62] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Desert Spirit", ["Level"] = 73, ["Repeatable"] = false},
        [63] = {["Type"] = "Kill", ["Amount"] = 1, ["Target"] = "Sand Terror", ["Level"] = 75, ["Repeatable"] = false}
    }
}
return quests
